Feature/boundary review frontend
DemocracyClub/EveryElection pull request #2032
Opened 2023-12-07 15:05 UTC by awdem

```[tasklist]
### PR Checklist
- [ ] Update changelog (ie https://keepachangelog.com/en/1.0.0/)
- [ ] References a specific issue or if not, describes the bug or feature in detail
- [ ] Note what card in Trello this work relates to
- [ ] Instructions for how reviewers can test the code locally
- [ ] Tests have been added and/or updated
- [ ] Screenshot of the feature/bug fix (if applicable)
- [ ] If any new text is added, it's internationalized
- [ ] Any new elements have aria labels
- [ ] No unintentional console.logs left behind after debugging
- [ ] Did I use the clear and concise names for variables and functions?
- [ ] Did I explain all possible solutions and why I chose the one I did?
- [ ] Added any comments to make new functions clearer
- [ ] Did I added or updated any new dependencies? Explain why.
- [ ] Did I update the package.json and/or Pipfile.lock version if relevant?
- [ ] Have I rebased with the latest version of master?
- [ ] Added PR labels
- [ ] Update any history/changelog file
- [ ] Update any documentation
- [ ] Update dev handbook
```

2024-01-26 12:57 UTC, GeoWill requested changes
This is looking good.
I like the layout of the list page. The filters are great. The detail page is a good base for adding more, um, detail... like maps, after May/GE.

There are a few changes that I've made comments about inline.

In answer to your questions:

> I wasn't sure if the filter logic should stay in filters.py or be added to the BR queryset model, but can easily move it over if that is better practice. Likewise, I wasn't sure if I should make tests for each filter option?

I'm not actually sure myself, but I think what you've done works (and looks) fine to me. @symroe might have more insight on this one. 

> I can add more properties to filter by or to display in the views if appropriate too

I don't think this is needed

2024-01-26 12:57 UTC, GeoWill commented on every_election/apps/organisations/templates/organisations/organisationboundaryreviews_list.html
> +{% endblock content %}2
Stray '2'

2024-01-26 12:57 UTC, GeoWill commented on every_election/apps/organisations/templates/organisations/organisationboundaryreviews_list.html
> +					<td><a href={{review.legislation_url}}>Link</a></td>
These might not be set, so we should only show a link if they exist.

2024-01-26 12:57 UTC, GeoWill commented on every_election/apps/organisations/templates/organisations/organisationboundaryreview_detail.html
> +				<dd>Read <a href="{{ boundary_review.legislation_url }}">the legislation</a> for this review</dd>
These urls might not be set (though the legislation _should_ exist) so we should have a conditional about whether so show the link

2024-01-26 12:57 UTC, GeoWill commented on every_election/apps/organisations/views/public.py
> +    paginate_by = 50
See comment above re. pagination.

2024-01-30 10:53 UTC, awdem commented on every_election/apps/organisations/templates/organisations/organisationboundaryreview_detail.html
> +				<dd><a href={{boundary_review.divisionset.organisation.get_absolute_url}}>{{boundary_review.divisionset.organisation.name}}</a></dd>
I noticed that BR that are currently in review weren't showing an org link or name because they don't have a division set yet so I removed the divisionset steps on these lines. Now they just use boundary_review.organisation for name and absolute_url.

2024-01-30 10:54 UTC, awdem commented on every_election/apps/organisations/templates/organisations/organisationboundaryreview_detail.html
> +				<dd>{{ boundary_review.status }}</dd>
Changed this to get_status_display to use the 'human-readable' status choices

2024-01-30 11:20 UTC, GeoWill commented on every_election/apps/organisations/templates/organisations/organisationboundaryreviews_list.html
> +	</ul>
This isn't working. Remove as discussed.

2024-01-30 11:21 UTC, GeoWill commented on every_election/apps/organisations/templates/organisations/organisationboundaryreviews_list.html
> +		<details {% if filter.data %}open=""{% endif %}>
Doesn't need a detail, or a distinction between filters and advanced filters/

2024-01-31 08:28 UTC, symroe commented on every_election/apps/organisations/templates/organisations/organisationboundaryreviews_list.html
> +					<td><a href={{review.legislation_url}}>Link</a></td>
This isn't a project that's really been optimised / designed for accessibility, but as a general rule the text of a link should be descriptive. This is because screen reader software can read out the links on the page for quick navigation. On this page the user will hear "link: Link. link: Link" when they could hear "link: Consultation, link: Legislation". I know these are in the table header, but I think it's still better to use descriptive links.

2024-01-31 08:33 UTC, symroe commented
> > I wasn't sure if the filter logic should stay in filters.py or be added to the BR queryset model, but can easily move it over if that is better practice. Likewise, I wasn't sure if I should make tests for each filter option?
> 
> I'm not actually sure myself, but I think what you've done works (and looks) fine to me. @symroe might have more insight on this one.

Are you talking about `organisation_filter` and `status_filter` here? If so, I think it's fine to be in the filter as is. I don't have hard rules, but broadly speaking if the query is above some complexity threashold (undefined!) then it's better on the model. In both of these cases you're applying a simple filter in a way that I would expect the filter to work, so I don't really see the value in having them on the model. `queryset.filter(status=value)` is just as simple to understand as `queryset.for_status(value)` or whatever.

2024-01-31 12:23 UTC, awdem commented
> > > I wasn't sure if the filter logic should stay in filters.py or be added to the BR queryset model, but can easily move it over if that is better practice. Likewise, I wasn't sure if I should make tests for each filter option?
> > 
> > 
> > I'm not actually sure myself, but I think what you've done works (and looks) fine to me. @symroe might have more insight on this one.
> 
> Are you talking about `organisation_filter` and `status_filter` here? If so, I think it's fine to be in the filter as is. I don't have hard rules, but broadly speaking if the query is above some complexity threashold (undefined!) then it's better on the model. In both of these cases you're applying a simple filter in a way that I would expect the filter to work, so I don't really see the value in having them on the model. `queryset.filter(status=value)` is just as simple to understand as `queryset.for_status(value)` or whatever.

Yes those are the two I meant. That makes sense! I was thinking that it could make sense to put them on the on model if they end up being used elsewhere in the codebase, but neither filter is complicated enough that it would even save that much on repetition.

2024-02-01 09:25 UTC, GeoWill reviewed
Looks great, and all working as expected. 
Couple more thoughts from playing around with it, happy for them to be fixed and all the fixup commits squashed.

2024-02-01 09:25 UTC, GeoWill commented on every_election/apps/organisations/templates/organisations/organisationboundaryreview_detail.html
> +					<dd>None</dd>
I think something like 'link missing' might be better here - when I look at the page and see `Consultation: None` it makes me think there wasn't a consultation/there's no legislation.

2024-02-01 09:25 UTC, GeoWill commented on every_election/apps/organisations/templates/organisations/organisationboundaryreviews_list.html
> +		</div>
The 'Filter: All' row looks a bit off to me. There's no choice there, so it's a little confusing. I wonder if it would make more sense to have a heading that just says 'Filters' instead 
![image](https://github.com/DemocracyClub/EveryElection/assets/20044500/49492def-d4a9-4069-8220-297f4af0f6e6)

2024-02-08 15:28 UTC, GeoWill approved these changes

2024-02-08 15:28 UTC, merged